name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request: # <--- Añade esto
    branches: [main]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "PromptLab CI funciona"